//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mokejimo_kortele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mokejimo_kortele()
        {
            this.Pirkimas = new HashSet<Pirkimas>();
        }
    
        public string Id { get; set; }
        public string Tipas { get; set; }
        public string Bankas { get; set; }
        public string Slaptažodžio_salt { get; set; }
        public string Slaptažodžio_hash { get; set; }
        public double Likutis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pirkimas> Pirkimas { get; set; }
    }
}
