//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nuolaidu_kortele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nuolaidu_kortele()
        {
            this.Pirkimas = new HashSet<Pirkimas>();
        }
    
        public string ID { get; set; }
        public string Savininko_vardas { get; set; }
        public string Savininko_pavarde { get; set; }
        public string Savininko_elpastas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pirkimas> Pirkimas { get; set; }
    }
}
