//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pirkimo_prekes
    {
        public int Preke { get; set; }
        public int Pirkimas { get; set; }
        public int Kiekis { get; set; }
    
        public virtual Pirkimas Pirkimas1 { get; set; }
        public virtual Preke Preke1 { get; set; }
    }
}
