//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pirkimas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pirkimas()
        {
            this.Pirkimo_prekes = new HashSet<Pirkimo_prekes>();
        }
    
        public int Id { get; set; }
        public byte[] Data { get; set; }
        public Nullable<int> Nuolaidu_kortele { get; set; }
        public string Apmokejimo_tipas { get; set; }
        public Nullable<int> Mokejimo_kortele { get; set; }
    
        public virtual Mokejimo_kortele Mokejimo_kortele1 { get; set; }
        public virtual Nuolaidu_kortele Nuolaidu_kortele1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pirkimo_prekes> Pirkimo_prekes { get; set; }
    }
}
