//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preke()
        {
            this.Pirkimo_prekes = new HashSet<Pirkimo_prekes>();
        }
    
        public int Barkodas { get; set; }
        public string Pavadinimas { get; set; }
        public double Kaina { get; set; }
        public string Svoris { get; set; }
        public string Kategorija { get; set; }
        public Nullable<int> Atributai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pirkimo_prekes> Pirkimo_prekes { get; set; }
    }
}
