//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDBEntities : DbContext
    {
        public ShopDBEntities()
            : base("name=ShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mokejimo_kortele> Mokejimo_kortele { get; set; }
        public virtual DbSet<Nuolaidu_kortele> Nuolaidu_kortele { get; set; }
        public virtual DbSet<Pirkimas> Pirkimas { get; set; }
        public virtual DbSet<Pirkimo_prekes> Pirkimo_prekes { get; set; }
        public virtual DbSet<Preke> Preke { get; set; }
    }
}
